<?php $collection = $this->getCollection();  ?>
<div class="page-title">
    <h1><?php echo $this->__('My Contacts') ?></h1>
</div>
<?php echo $this->getToolbarHtml(); ?>
<table class="data-table" id="my-custom-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Id') ?></th>
            <th><span class="nobr"><?php echo $this->__('Name') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Email') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Update') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Delete') ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($collection as $item): ?>
        <tr>
            <td><span class="nobr"><?php echo $item->getID(); ?></span></td>
            <td><?php echo $item->getName() ?></td>
            <td><?php echo $item->getEmail() ?></td>
            <td><a href="<?php echo $this->getUrl('contact/view', array('id'=> $item->getId())); ?>">Update</a></td>
            <td><a href="<?php echo $this->getUrl('contact/delete', array('id'=> $item->getId())); ?>">Delete</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->getToolbarHtml(); ?>